// Catálogo de temas. Adicionar um tema novo = adicionar um entry aqui
// + um snippet em ThemeDecorations para a decoração visual (opcional).

export const THEMES = {
  romantic: {
    id: 'romantic',
    name: 'Romântico',
    description: 'Tons rosados, suaves e apaixonados.',
    emoji: '💖',
    decoration: 'hearts',
    vars: {
      '--letter-bg': 'linear-gradient(135deg, #fff1f5 0%, #ffe4ec 60%, #ffd6e8 100%)',
      '--letter-surface': '#ffffff',
      '--letter-surface-soft': '#fff7fa',
      '--letter-ink': '#3a1d2a',
      '--letter-ink-soft': '#7a5060',
      '--letter-accent': '#e11d74',
      '--letter-accent-soft': '#f9a8d4',
      '--letter-border': 'rgba(225, 29, 116, 0.18)',
      '--letter-heading-font': 'var(--font-playfair), Georgia, serif',
      '--letter-body-font': 'var(--font-inter), system-ui, sans-serif',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, branco, foco total na mensagem.',
    emoji: '🤍',
    decoration: 'none',
    vars: {
      '--letter-bg': 'linear-gradient(180deg, #fafafa 0%, #f4f4f5 100%)',
      '--letter-surface': '#ffffff',
      '--letter-surface-soft': '#fafafa',
      '--letter-ink': '#0a0a0a',
      '--letter-ink-soft': '#52525b',
      '--letter-accent': '#18181b',
      '--letter-accent-soft': '#d4d4d8',
      '--letter-border': 'rgba(0,0,0,0.08)',
      '--letter-heading-font': 'var(--font-inter), system-ui, sans-serif',
      '--letter-body-font': 'var(--font-inter), system-ui, sans-serif',
    },
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    description: 'Papel envelhecido, tons sépia, nostalgia pura.',
    emoji: '📜',
    decoration: 'paper',
    vars: {
      '--letter-bg': 'linear-gradient(180deg, #f3e9d2 0%, #e8d9b8 100%)',
      '--letter-surface': '#fbf3df',
      '--letter-surface-soft': '#f3e9d2',
      '--letter-ink': '#3b2a16',
      '--letter-ink-soft': '#7a5c39',
      '--letter-accent': '#9a6b2f',
      '--letter-accent-soft': '#d6b07a',
      '--letter-border': 'rgba(122, 92, 57, 0.25)',
      '--letter-heading-font': '"Playfair Display", Georgia, serif',
      '--letter-body-font': '"Playfair Display", Georgia, serif',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'Misterioso, elegante, com brilho noturno.',
    emoji: '🌙',
    decoration: 'stars',
    vars: {
      '--letter-bg': 'radial-gradient(ellipse at top, #1e1b4b 0%, #0b0b14 100%)',
      '--letter-surface': '#16162b',
      '--letter-surface-soft': '#1d1d36',
      '--letter-ink': '#f4f4f5',
      '--letter-ink-soft': '#a1a1aa',
      '--letter-accent': '#c4b5fd',
      '--letter-accent-soft': '#7c3aed',
      '--letter-border': 'rgba(196, 181, 253, 0.25)',
      '--letter-heading-font': 'var(--font-playfair), Georgia, serif',
      '--letter-body-font': 'var(--font-inter), system-ui, sans-serif',
    },
  },
  anime: {
    id: 'anime',
    name: 'Anime',
    description: 'Pastéis vibrantes, kawaii e cheio de vida.',
    emoji: '🌸',
    decoration: 'sakura',
    vars: {
      '--letter-bg': 'linear-gradient(135deg, #ffe4f1 0%, #e0e7ff 60%, #ddd6fe 100%)',
      '--letter-surface': '#ffffff',
      '--letter-surface-soft': '#fdf2ff',
      '--letter-ink': '#1e1b4b',
      '--letter-ink-soft': '#6d28d9',
      '--letter-accent': '#ec4899',
      '--letter-accent-soft': '#fbcfe8',
      '--letter-border': 'rgba(236, 72, 153, 0.25)',
      '--letter-heading-font': 'var(--font-playfair), Georgia, serif',
      '--letter-body-font': 'var(--font-inter), system-ui, sans-serif',
    },
  },
  birthday: {
    id: 'birthday',
    name: 'Aniversário',
    description: 'Festivo, colorido, com clima de celebração.',
    emoji: '🎉',
    decoration: 'confetti',
    vars: {
      '--letter-bg': 'linear-gradient(135deg, #fef9c3 0%, #fde68a 50%, #fca5a5 100%)',
      '--letter-surface': '#ffffff',
      '--letter-surface-soft': '#fffbeb',
      '--letter-ink': '#451a03',
      '--letter-ink-soft': '#92400e',
      '--letter-accent': '#dc2626',
      '--letter-accent-soft': '#fecaca',
      '--letter-border': 'rgba(220, 38, 38, 0.25)',
      '--letter-heading-font': 'var(--font-playfair), Georgia, serif',
      '--letter-body-font': 'var(--font-inter), system-ui, sans-serif',
    },
  },
}

export const THEME_LIST = Object.values(THEMES)
export const THEME_IDS = Object.keys(THEMES)

export function getTheme(id) {
  return THEMES[id] || THEMES.romantic
}
